[2024-12-15T13:59:48.194-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T13:59:48.197-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multiple_dags.task_a manual__2024-12-15T18:59:46.975592+00:00 [queued]>
[2024-12-15T13:59:48.199-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multiple_dags.task_a manual__2024-12-15T18:59:46.975592+00:00 [queued]>
[2024-12-15T13:59:48.199-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-15T13:59:48.203-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_a> on 2024-12-15 18:59:46.975592+00:00
[2024-12-15T13:59:48.204-0500] {standard_task_runner.py:72} INFO - Started process 34514 to run task
[2024-12-15T13:59:48.207-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'multiple_dags', 'task_a', 'manual__2024-12-15T18:59:46.975592+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/multiple_dags.py', '--cfg-path', '/var/folders/jw/j912b4gd5xj0c7j8p3syth7r0000gn/T/tmp10_w6fel']
[2024-12-15T13:59:48.209-0500] {standard_task_runner.py:105} INFO - Job 42: Subtask task_a
[2024-12-15T13:59:48.222-0500] {task_command.py:467} INFO - Running <TaskInstance: multiple_dags.task_a manual__2024-12-15T18:59:46.975592+00:00 [running]> on host mac-4031.lan
[2024-12-15T13:59:48.234-0500] {abstractoperator.py:780} ERROR - Exception rendering Jinja template for task 'task_a', field 'bash_command'. Template: 'taskA.sh'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 772, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-12-15T13:59:48.234-0500] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3115, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3534, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1430, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 772, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-12-15T13:59:48.236-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=multiple_dags, task_id=task_a, run_id=manual__2024-12-15T18:59:46.975592+00:00, execution_date=20241215T185946, start_date=20241215T185948, end_date=20241215T185948
[2024-12-15T13:59:48.239-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T13:59:48.239-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task task_a (taskA.sh; 34514)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3115, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3534, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1430, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 772, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-12-15T13:59:48.270-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T13:59:48.277-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T13:59:48.278-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
