[2024-12-19T17:30:46.375-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T17:30:46.379-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_python_etl_dag.clean_the_data manual__2024-12-19T22:30:42.088998+00:00 [queued]>
[2024-12-19T17:30:46.381-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_python_etl_dag.clean_the_data manual__2024-12-19T22:30:42.088998+00:00 [queued]>
[2024-12-19T17:30:46.381-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-19T17:30:46.386-0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): clean_the_data> on 2024-12-19 22:30:42.088998+00:00
[2024-12-19T17:30:46.390-0500] {standard_task_runner.py:72} INFO - Started process 78848 to run task
[2024-12-19T17:30:46.396-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_python_etl_dag', 'clean_the_data', 'manual__2024-12-19T22:30:42.088998+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/var/folders/jw/j912b4gd5xj0c7j8p3syth7r0000gn/T/tmpw2meljq3']
[2024-12-19T17:30:46.400-0500] {standard_task_runner.py:105} INFO - Job 77: Subtask clean_the_data
[2024-12-19T17:30:46.433-0500] {task_command.py:467} INFO - Running <TaskInstance: executing_python_etl_dag.clean_the_data manual__2024-12-19T22:30:42.088998+00:00 [running]> on host mac-4952.lan
[2024-12-19T17:30:46.456-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='venkatesh' AIRFLOW_CTX_DAG_ID='executing_python_etl_dag' AIRFLOW_CTX_TASK_ID='clean_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T22:30:42.088998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T22:30:42.088998+00:00'
[2024-12-19T17:30:46.457-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T17:30:46.463-0500] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/apple/airflow/dags/etl.py", line 36, in clean_data
    clean_sales_data = sales_data[(sales_data['sale_id'].notnull()) & (sales_data['product_id'].notnull())]
TypeError: 'NoneType' object is not subscriptable
[2024-12-19T17:30:46.468-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=executing_python_etl_dag, task_id=clean_the_data, run_id=manual__2024-12-19T22:30:42.088998+00:00, execution_date=20241219T223042, start_date=20241219T223046, end_date=20241219T223046
[2024-12-19T17:30:46.472-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T17:30:46.472-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 77 for task clean_the_data ('NoneType' object is not subscriptable; 78848)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/apple/airflow/dags/etl.py", line 36, in clean_data
    clean_sales_data = sales_data[(sales_data['sale_id'].notnull()) & (sales_data['product_id'].notnull())]
TypeError: 'NoneType' object is not subscriptable
[2024-12-19T17:30:46.503-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-19T17:30:46.510-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T17:30:46.511-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
